In [1]:
# Introduce numpy package
import numpy as np

In [13]:
# introducing dictionary 
d= {"1": "A"}

In [3]:
# Numpy Arrays
set1 = np.array([2,4,6,8,10])
print (set1)
print(set1[0])
print(set1[2:])
print (set1[:-3])
# replacing a specific value in list
set1[3]= 12
print (set1)

[ 2  4  6  8 10]
2
[ 6  8 10]
[2 4]
[ 2  4  6 12 10]


In [6]:
# Numpy multidimensional arrays with different lists using []
set2= np.array([[2,4,6],
               [8,10,12],
               [14,16,18]])
print(set2[0]) # to get list 1
print(set2[0,1]) # to get second value in list1

[2 4 6]
4
(3, 3)
9


In [9]:
set3= np.array([[[1,2,3,4],
               [1,2,3,4],
               [1,2,3,4]],
              [[2,4,6,8],
              [2,4,6,8],
              [2,4,6,8]]])
print(set3.shape) # type of dimensions (x,y,z) x= no of lists, y= consisting of sub lists each in x, z= elements per list 
print(set3.size) # total number of elements
print(set3.ndim) # number of dimensions
print(set3.dtype) # data type

(2, 3, 4)
24
3
int32


In [14]:
# changing data types into string
set4= np.array([[2,4,6],
               [4,"Car",6],
               [1,2,4]])
print (set4.dtype)
print (type(set4[0][0])) 
# specify what data type ( changing str to int)
set5= np.array([[2,4,6],
               [4,"5",6],
               [1,2,4]], dtype=np.int32) # to float use float32, to str use= "<U21"
print (set5.dtype)
set6= np.array([[2,4,6],
               [4,d,6],
               [1,2,4]])
print (set6.dtype) #  using dictionary would make dtype= object

<U11
<class 'numpy.str_'>
int32
object


In [23]:
# # filling out with default values (x,y,z),i=what number to fill it with
set7=np.full((2,3,4),9) 
set7

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [26]:
# filling out with zeros
set8=np.zeros((2,3,4))
set8

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
# filling out with ones
set9=np.ones((2,3,4))
set9

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
# filling out without intializing the values
set10=np.empty((2,3,3))
set10

array([[[4.45057637e-308, 9.34604358e-307, 9.34605037e-307],
        [1.11260483e-306, 1.78019354e-306, 4.45066125e-308],
        [9.34605037e-307, 1.60220393e-306, 1.24611674e-306]],

       [[4.45057637e-308, 9.34597567e-307, 2.22523004e-306],
        [2.13620264e-306, 4.45063578e-308, 1.37961302e-306],
        [8.45596650e-307, 5.73116149e-322, 9.34608432e-307]]])

In [35]:
# generating values sequence
set11=np.arange(0,100,5) # (a,b,c)= (start value, end value, step size )
set11

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [37]:
set12=np.linspace(0,1000,10) # (start value, end value, how many values to generate)
set12

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [39]:
# using Nan and Inf
print(np.nan) # to fill out null values in a data set
print(np.inf) # for values divided by 0
# to indentify
print (np.isnan(np.nan)) 
print (np.sqrt(-1))
print(np.isinf(np.inf))
print (np.array([10])/0)

nan
inf
True
nan
True
[inf]


C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


In [42]:
# performing mathematical operations 
l1= [1,2,3,4]
l2= [5,6,7,8]
# converting list to arrays 
a1=np.array(l1) 
a2=np.array(l2)

print(l1*4) # duplicates list 4 times
print(a1*4) # multiplies each values in array by 4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[ 4  8 12 16]


In [44]:
#print (l1+2) # unable to add lists
print (a1+2) # adds each values in array by 2

[3 4 5 6]


In [45]:
print (l1+l2) # add both lists into a single list
print (a1/a2) # divides each values among themselves

[1, 2, 3, 4, 5, 6, 7, 8]
[0.2        0.33333333 0.42857143 0.5       ]


In [47]:
# additing a list into an array
set13= np.array([1,2,3])
set13=np.append(set13, [4,5,6])
set13

array([1, 2, 3, 4, 5, 6])

In [48]:
# Inserting a list into an array
set14=np.insert (set13,6,[7,8,9])
set14

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# Delelting a value from an array
print(np.delete(set14,1)) # delete number position

[1 3 4 5 6 7 8 9]


In [57]:
print(np.delete(set6,1,0)) # delete second row

[[2 4 6]
 [1 2 4]]


In [58]:
print (np.delete(set3,0,0)) # delete first row

[[[2 4 6 8]
  [2 4 6 8]
  [2 4 6 8]]]


In [86]:
# reshaping an array
set15=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
print(set15)
set15.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [66]:
set16= print(set15.reshape((4,3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [77]:
set17=print(set15.flatten()) # display one dimensional array 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [87]:
set18= print(set15.ravel()) # same function but returns only a flat view

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [78]:
var1=set15.flatten()
var1[2]= 50
print (var1)
print (set15)

[ 1  2 50  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [88]:
var2=set15.ravel()
var2[2]= 50
print (var2)
print (set15)

[ 1  2 50  4  5  6  7  8  9 10 11 12]
[[ 1  2 50  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [112]:
set19= np.array([[1,2,3,4,20],
                 [5,6,7,8,30],
                 [9,10,11,12,13],
                 [14,15,16,17,18]])
set19

array([[ 1,  2,  3,  4, 20],
       [ 5,  6,  7,  8, 30],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18]])

In [104]:
print(set19.T) # switch axes

[[ 1  5  9 14]
 [ 2  6 10 15]
 [ 3  7 11 16]
 [ 4  8 12 17]
 [20 30 13 18]]


In [111]:
print(set19.swapaxes(1,0)) # specifiy which axes to swap

[[ 1  5  9 14]
 [ 2  6 10 15]
 [ 3  7 11 16]
 [ 4  8 12 17]
 [20 30 13 18]]


In [141]:
# Array Merge
set20=np.array([[1,2,3,4],
                [5,6,7,8]])
set21=np.array([[9,10,11,12],
              [13,14,15,16]])

In [122]:
print(np.concatenate((set20,set21), axis=0)) # Merge into 1 array; 0= rows, 1= columns
print(np.concatenate((set20,set21),axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [130]:
# stack adds a new dimension
print(np.vstack((set20,set21))) # vertical
print(np.hstack((set20,set21))) # horizontal

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [137]:
# Splitting arrays
print(np.split(set20, 2, axis =0)) # splitting into 2 arrays

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [142]:
# aggregate functions
print(set20.min())
print(set20.max())
print(set20.mean())
print(np.median(set20))
print(set20.std())

1
8
4.5
4.5
2.29128784747792


In [144]:
#NumPY Random
print(np.random.randint(100))

50


In [145]:
print(np.random.randint(90,100, size=(2,3,4))) # 90 min, 100 max 

[[[97 94 94 95]
  [92 95 98 99]
  [97 99 98 99]]

 [[99 90 97 95]
  [92 99 96 96]
  [92 90 91 92]]]


In [146]:
print(np.random.binomial(10, p=0.2, size=(5,10))) # random by binmial

[[2 1 1 3 2 5 1 1 1 3]
 [1 2 4 2 2 1 4 2 4 2]
 [1 1 4 0 0 1 2 1 1 2]
 [3 3 1 2 2 3 3 3 2 1]
 [1 2 2 0 2 3 2 3 1 4]]


In [148]:
print(np.random.normal(loc=150, scale=10, size=(5,10))) # random by normal

[[140.88820877 136.91828751 153.60618336 150.56922635 161.92051646
  158.37471694 148.84476896 157.74827253 153.45594865 165.90228823]
 [142.86925355 137.33208536 173.31151604 141.11441603 156.78612629
  174.59784007 153.22360068 160.78910405 135.50609668 152.47402852]
 [164.37013319 136.41577859 153.80125901 145.13845841 158.25160532
  139.42093489 146.06492822 141.08751297 158.9276709  153.75509197]
 [154.85508995 147.61131847 165.57692225 145.63722329 151.90076352
  138.79664991 152.60581266 152.95067899 141.80977225 148.91347871]
 [147.8341498  141.17954221 153.42815027 143.69672122 158.29224666
  161.07217492 138.17114693 147.28371658 156.24460755 166.9380023 ]]


In [149]:
print(np.random.choice([20,40,60,80], size =(5,10))) # random by choice

[[20 60 80 80 40 20 20 40 20 60]
 [40 20 80 20 80 80 80 60 80 80]
 [80 60 20 60 80 60 40 60 20 80]
 [40 20 20 20 20 80 20 40 20 20]
 [40 40 80 60 60 80 60 20 80 60]]


In [152]:
#exporting and Importing
#np.save("Numpy Implementation.npy",set20) # save as numpy 

In [ ]:
#np.load("Numpy Implementation.npy")  # load as numpy

In [ ]:
#np.savetext("Numpy Implementation.csv", set20, delimiter= ",") # Save as txt file