## Ololade Adetula
## Functional API

In [1]:
# Importing environment supporting tensorflow
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
# Packages implemented 
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
# Defining Functional Model
inputs = keras.Input(shape=(28,28))
flatten = keras.layers.Flatten()
dense1 = keras.layers.Dense(128, activation='relu')

dense2 = keras.layers.Dense(10, activation='softmax', name="category_output")
dense3 = keras.layers.Dense(1, activation='sigmoid', name="leftright_output")

In [3]:
x = flatten(inputs)
x = dense1(x)
outputs1 = dense2(x)
outputs2 = dense3(x)

model = keras.Model(inputs=inputs, outputs=[outputs1, outputs2], name="mnist_model")

In [4]:
model.summary()

Model: "mnist_model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 28, 28)]             0         []                            
                                                                                                  
 flatten (Flatten)           (None, 784)                  0         ['input_1[0][0]']             
                                                                                                  
 dense (Dense)               (None, 128)                  100480    ['flatten[0][0]']             
                                                                                                  
 category_output (Dense)     (None, 10)                   1290      ['dense[0][0]']               
                                                                                        

In [5]:
# loss and optimizer
loss1 = keras.losses.SparseCategoricalCrossentropy(from_logits=False)
loss2 = keras.losses.BinaryCrossentropy(from_logits=False)
optim = keras.optimizers.Adam(lr=0.001)
metrics = ["accuracy"]

losses = {
    "category_output": loss1,
    "leftright_output": loss2,
}

model.compile(loss=losses, optimizer=optim, metrics=metrics)

In [6]:
# create data with 2 labels
mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# 0=left, 1=right
y_leftright = np.zeros(y_train.shape, dtype=np.uint8)
for idx, y in enumerate(y_train):
    if y > 5:
        y_leftright[idx] = 1

print(y_train.dtype, y_train[0:20])
print(y_leftright.dtype, y_leftright[0:20])

y= {"category_output": y_train,
    "leftright_output": y_leftright }

uint8 [5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
uint8 [0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1]


In [7]:
# training set
model.fit(x_train, y=y, epochs=5,
          batch_size=64, verbose=2)

Epoch 1/5
938/938 - 8s - loss: 0.5128 - category_output_loss: 0.3131 - leftright_output_loss: 0.1998 - category_output_accuracy: 0.9126 - leftright_output_accuracy: 0.9270 - 8s/epoch - 8ms/step
Epoch 2/5
938/938 - 3s - loss: 0.2409 - category_output_loss: 0.1426 - leftright_output_loss: 0.0983 - category_output_accuracy: 0.9590 - leftright_output_accuracy: 0.9671 - 3s/epoch - 3ms/step
Epoch 3/5
938/938 - 3s - loss: 0.1795 - category_output_loss: 0.1031 - leftright_output_loss: 0.0765 - category_output_accuracy: 0.9699 - leftright_output_accuracy: 0.9738 - 3s/epoch - 3ms/step
Epoch 4/5
938/938 - 3s - loss: 0.1447 - category_output_loss: 0.0802 - leftright_output_loss: 0.0645 - category_output_accuracy: 0.9758 - leftright_output_accuracy: 0.9784 - 3s/epoch - 3ms/step
Epoch 5/5
938/938 - 3s - loss: 0.1185 - category_output_loss: 0.0636 - leftright_output_loss: 0.0549 - category_output_accuracy: 0.9808 - leftright_output_accuracy: 0.9811 - 3s/epoch - 3ms/step


In [8]:
# list with 2 predictions
predictions = model.predict(x_test)
len(predictions)

313/313 [==============================] - 1s 2ms/step


2

In [9]:
# prediction metric
prediction_category = predictions[0]
prediction_lr = predictions[1]

pr_cat = prediction_category[0:20]
prediction_lr = prediction_lr[0:20]

labels_cat = np.argmax(pr_cat, axis=1)
labels_lr = np.array([1 if p >= 0.5 else 0 for p in prediction_lr])

In [10]:
print(y_test[0:20])
print(labels_cat)
print(labels_lr)

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0]
